### ISSUE TITLE
setproctitle doesn't change "Process Name" in Activity Monitor.app on OS X

### ISSUE THREAD

**Issue by dvarrazzo** [dvarrazzo/py-setproctitle#10]
Originally submitted by **danlarkinwhat** as **issue 10**:

On OS X, setproctitle affects the output from /bin/ps, but not the &quot;Process Name&quot; in Activity Monitor.app.

Here's an informative thread discussing this issue on the node.js mailing list:
http://groups.google.com/group/nodejs/browse_thread/thread/cfe27a56d1875b52

The penultimate post on that thread includes a patch that supposedly fixes the problem -- perhaps you could think about including something similar.

**Comment by santagada** [comment]
there is also this code https://stackoverflow.com/questions/4217947/setting-process-name-on-mac-os-x-at-runtime/7458145#7458145

I will take a look if I can make this work and submit a patch, xonsh shell uses setproctitle and I can't filter it on activity monitor.

**Comment by kutsan** [comment]
I don't know if it's related about this issue but changing process name through this library wouldn't affect tmux's window title in macOS. Although it works on Linux systems. As OP referred I can see the new process name in the output of `ps`.

**Comment by the-real-tokai** [comment]
I usually workaround this situation by creating a hardlink to the Python executable as kludge, then use that hardlink to launch the script; the hardlink can have any name and that's how it shows up in the various places then. At least for permanently/ long running scripts this can be helpful (else you just see a whole bunch of "Pythons" in Activity Monitor/ Little Snitch/ etc. and don't know what's going on. ;) )

**Comment by charterchap** [comment]
It does show up fine in htop, so if you can live with that instead of activity monitor...
