### ISSUE TITLE
Version 1.2.2 not working on Fedora 33

### ISSUE THREAD

**Issue by VainlyStrain** [dvarrazzo/py-setproctitle#100]
Hi!

Release 1.2.2 fails to set a new process name on Fedora 33, x86-64, Python 3.9.

Downgrading to 1.2.1 resolves the issue.

Used function: setproctitle("title")

Please tell me if you need more data :)

**Comment by VainlyStrain** [comment]
To clarify, there is no error message, the title just doesn't show up.

**Comment by dvarrazzo** [comment]
as per README, try setting `SPT_DEBUG=1`: you should get diagnostic messages.

**Comment by VainlyStrain** [comment]
Hi!

Just upgraded again to the new version, and it is working fine now. Maybe that earlier bug was caused by a major system upgrade I did some months ago, and rebuilding it resolved the conflict.

Closing it, since it is fixed and unrelated to this project.
