### ISSUE TITLE
MacOS Python3.8.2 raising Symbol not found: _Py_GetArgcArgv

### ISSUE THREAD

**Issue by Jorricks** [dvarrazzo/py-setproctitle#103]
I have a MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports).
I used the default XCode python3 executable to create a venv.
This is Python3.8.2.
When I install setproctitle, I would get `  #error architecture not supported`, which I fixed with setting `export ARCHFLAGS="-arch x86_64"` before running `pip install`.
However, now I am getting the following when I try to import it:
```
Python 3.8.2 (default, Aug 25 2020, 09:23:57) 
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setproctitle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(~/.venv/airflow_dev/lib/python3.8/site-packages/setproctitle.cpython-38-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
  Referenced from: ~/.venv/airflow_dev/lib/python3.8/site-packages/setproctitle.cpython-38-darwin.so
  Expected in: flat namespace
 in ~/.venv/airflow_dev/lib/python3.8/site-packages/setproctitle.cpython-38-darwin.so
 ```

I have been googling a bit and found that [a person mentioned](https://stackoverflow.com/a/60148373/2277445) this is fixed by Python 3.8.5, but not really sure what fixed it?
Currently I don't have access to Python 3.8.5 (company laptop) and was wondering if there were any other options out there to fix it.

**Comment by Modjular** [comment]
I'm also running into this error:
 - 2021 MPB M1
 - Monterey 12.2
 - Python 3.8.9 (preinstalled)
 - pipenv

```python
tony@Tonys-MacBook-Pro stitcher % pipenv run python          
Python 3.8.9 (default, Feb 18 2022, 07:45:33) 
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> import setproctitle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/tony/.local/share/virtualenvs/stitcher-8SKz3ZHs/lib/python3.8/site-packages/setproctitle.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_Py_GetArgcArgv'
>>> 
```
