### ISSUE TITLE
not possible to preserve original null bytes

### ISSUE THREAD

**Issue by spaceone** [dvarrazzo/py-setproctitle#107]
Arguments are originally separated by null bytes in Linux.
This library replaces them with spaces.

foo.py
```python
import os

org = open(f'/proc/{os.getpid()}/cmdline', 'rb').read()
print(org)

import setproctitle  # noqa: E402

print(open(f'/proc/{os.getpid()}/cmdline', 'rb').read())

print(repr(setproctitle.getproctitle()))
setproctitle.setproctitle(org.decode('ASCII'))
print(repr(setproctitle.getproctitle()))
```

```bash
$ python3 foo.py --foo --bar -x baz
b'python3\x00foo.py\x00--foo\x00--bar\x00-x\x00baz\x00'
b'python3 foo.py --foo --bar -x baz\x00'
'python3 foo.py --foo --bar -x baz'
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    setproctitle.setproctitle(org.decode('ASCII'))
ValueError: embedded null character
```

Some libraries depend on the null byte when they are parsing. This is especially annoying when one wants to use `setproctitle` for backwards compatibility with those parsers (e.g. in a nagios or prometheus check).

Maybe it can be changed so that one can specify null bytes e.g. by passing a list of arguments instead of a str?

**Comment by dvarrazzo** [comment]
No, it's not possible to preserve null chars: the proc fs will only display up to the first null.
