### ISSUE TITLE
Segfault on macOS 12.5 / setproctitle 1.3.0

### ISSUE THREAD

**Issue by ekolve** [dvarrazzo/py-setproctitle#111]
I am getting segfaults when running gunicorn 20.1.0 and setproctitle 1.3.0.  My environment is Python3.10/macOS 12.5 MacBookPro M1.  To reproduce create a file named `test.py` with the following contents:
```
def app(environ, start_response):
    """Simplest possible application object"""
    data = b'Hello, World!\n'
    status = '200 OK'
    response_headers = [
        ('Content-type', 'text/plain'),
        ('Content-Length', str(len(data)))
    ]
    start_response(status, response_headers)
    return iter([data])
```
Install gunicorn==20.1.0 setproctitle==1.3.0. Then execute the command:

`gunicorn test:app`

I receive the following output:
```
[2022-08-03 12:12:04 -0700] [99378] [INFO] Starting gunicorn 20.1.0
[2022-08-03 12:12:04 -0700] [99378] [INFO] Listening at: http://127.0.0.1:8000 (99378)
[2022-08-03 12:12:04 -0700] [99378] [INFO] Using worker: sync
[2022-08-03 12:12:06 -0700] [99378] [WARNING] Worker with pid 99380 was terminated due to signal 11
[2022-08-03 12:12:07 -0700] [99378] [WARNING] Worker with pid 99382 was terminated due to signal 11
```
If I downgrade the version of setproctitle to 1.2.3, there is no segfault.  I did some investigation locally to try to isolate which commit is the cause of this and I believe that c993231c07492bfe5a80229c05087a6a5f18de0a is the commit where this was introduced.  If I install the package using `python setup.py install` for that commit, the segfault occurs.  If I install 87378de1a29ec3ff1f2d0245a8a6722c17e529f3 (commit immediately preceding it on master), the error does not occur.

I can't get the error to reproduce as a standalone script (just calling `setproctittle()`), so I am not clear on why the error only occurs when running with gunicorn.

**Comment by ekolve** [comment]
I was able to reproduce this in a standalone script:

```python
import multiprocessing as mp
from setproctitle import setproctitle
def foo():
    setproctitle('title in child')

if __name__ == '__main__':
    setproctitle('title in parent')
    mp.set_start_method('fork') 
    p = mp.Process(target=foo)
    p.start()
    p.join()
    print(p.exitcode) # returns -11 on failure 0 on success
```

Note the `set_start_method` getting set to `fork`.  If this is set to `spawn`, no error occurs.  If the call to `setproctitle()` in the parent process is removed, no error occurs either.  Downgrading to `1.2.3` also fixes the issue for this example.

**Comment by dvarrazzo** [comment]
Thank you for the repro! @gershnik would you be able to look into this problem?

**Comment by gershnik** [comment]
Yep, will do.

**Comment by dvarrazzo** [comment]
@gershnik thank you very much! I have created a [fix-111 branch](https://github.com/dvarrazzo/py-setproctitle/tree/fix-111) with the repro proposed by @ekolve in the tests.

**Comment by gershnik** [comment]
@dvarrazzo Fixed and PR submitted

**Comment by dvarrazzo** [comment]
Thank you @gershnik! Merging, will release 1.3.1 packages later today :+1:

**Comment by vcunat** [comment]
This test now consistently fails for us (on both macOS archs), possibly triggered by macOS upgrade.  It goes like
```
[...]
        out, err = proc.communicate(script and script.encode())
        if 0 != proc.returncode:
            if out:
                print(out.decode("utf8", "replace"), file=sys.stdout)
            if err:
                print(err.decode("utf8", "replace"), file=sys.stderr)
>           pytest.fail("test script failed")
E           Failed: test script failed

tests/conftest.py:154: Failed
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
AssertionError: p.exitcode is -11

=========================== short test summary info ============================
FAILED tests/setproctitle_test.py::test_fork_segfault - Failed: test script failed
FAILED tests/setproctitle_test.py::test_thread_fork_segfault - Failed: test script failed
============ 2 failed, 14 passed, 11 skipped, 1 deselected in 1.27s ============
```

**Comment by dvarrazzo** [comment]
@vcunat this bug is closed. New macOS, new story.
