### ISSUE TITLE
add support for py27 and py36

### ISSUE THREAD

**Issue by slashburygin** [dvarrazzo/py-setproctitle#130]
Hi. This is beautiful project, but we use openstack project in our infrastructure and want to use your project in it.
It will be perfectly if you add support for this python versions, espeсially for py27

**Comment by dvarrazzo** [comment]
Hello,

Python 2.7 has been out of support for several years. Most infrastructure for build and test won't even support it anymore. PyPI is not guaranteed to serve it anymore. Most OS won't provide packages for it.

It is a major commitment and I have no intention to do it for free. You can contact privately to agree on a commercial plan.
