### ISSUE TITLE
Set/change titles for other processes?

### ISSUE THREAD

**Issue by brahn** [dvarrazzo/py-setproctitle#132]
Is there a way to use this library to set titles for _other_ processes/threads?

Context:

 I am working on a project that uses [Celery](https://docs.celeryq.dev/en/stable/) to manage asynchronous tasks, and when running locally on a mac (typical for project developers) the workers all show up in Activity Monitor as "python" with no further detail.  I can use `ps` to see more detail about a particular process, but this is not particularly ergonomic. 

I'd love to build a little script that finds all processes that matching some criteria (e.g. the process is in the list output of `ps axwwo user,pid,ppid,pgid,command | grep "\/venv\/bin\/celery"`) and change the process title as displayed in Activity Monitor.

Suggestions for other approaches would also be most welcome!

**Comment by dvarrazzo** [comment]
You can't change a memory's process from another process. You have to do something from within the Celery process.

I am not familiar with how celery processes are managed: I think you should talk with them to figure out how to run setproctitile from within the project.

**Comment by brahn** [comment]
Thanks!

**Comment by gershnik** [comment]
For completeness it is probably possible to say attach lldb to a given Python process and, using lldb commands load some dynamic library that would perform an equivalent of what setproctitle is doing. Then detach lldb.
Then script it all so you could say `setproctitle pid "title"` on the command line. 
Creating something like this would be a major undertaking though. 
Far easier just to modify the Python code you are running or make Celery do some pre-load steps if possible.
