### ISSUE TITLE
Segfault after fork while using python-ldap on OSX 12.6

### ISSUE THREAD

**Issue by dwinings** [dvarrazzo/py-setproctitle#133]
I spent quite some time chasing ghosts on this one. I was dealing with an issue where flask-app-builder (with gunicorn) was segfaulting workers when ldap auth was enabled on OS X 12.6, but not on linux. python-ldap was also working just fine in a shell and in toy scripts. I eventually realized that my crash only occurred post-fork, so I came up with the following script, which still worked:

```
import os

def do_some_ldap():
    import ldap
    con = ldap.initialize('ldaps://ldap.mydomain.com')
    con.simple_bind_s(*('cn=admin,dc=mydomain,dc=com', 'pass', None, None))
    resp = con.search_s("ou=People,dc=mydomain,dc=com", ldap.SCOPE_SUBTREE, "(sn=me)" , ["memberOf"])
    print(resp)

# setproctitle.setproctitle('parent')
pid = os.fork()
if pid == 0:  # child
    setproctitle.setproctitle('child')
    print("Ldapping from child...")
    do_some_ldap()
else:
    child_pid, child_exit = os.wait()
    print(f"Child [{child_pid}] exited with code {child_exit}")
    print("Ldapping from parent...")
    do_some_ldap()
```

This script ran correctly (ldap worked on both sides of the fork, exit code 0, etc). I was trying to figure out what on earth gunicorn could be doing to make its forks behave differently and I found a reference to issue #111 , which I realized was likely what I had found. Sure enough, adding so much as `import setproctitle` to the top of the script was enough to cause the child to segfault reliably on the call to `simple_bind_s`. When I downgraded my installed version of `setproctitle` to `1.2.3` from `1.3.2`, there were no crashes.

This crash only occurs with a present ldap server. I am running python 3.9.1. Here is a full list of installed packages for the virtual environment that I reproduced this with:
[pip_freeze.txt](https://github.com/dvarrazzo/py-setproctitle/files/11986243/pip_freeze.txt)

**Comment by gershnik** [comment]
Thank you for reporting!

From macOS `man fork`

>CAVEATS
>     There are limits to what you can do in the child process.  To be totally safe you should restrict yourself to only executing async-signal safe operations until such time as one of the exec functions is
>     called.  All APIs, including global data symbols, in any framework or library should be assumed to be unsafe after a fork() unless explicitly documented to be safe or async-signal safe.  If you need to use
>     these frameworks in the child process, you must exec.  In this situation it is reasonable to exec yourself.

And from https://docs.python.org/3/library/multiprocessing.html

> The fork start method should be considered unsafe as it can lead to crashes of the subprocess.

See also lengthy discussion in #113 

Fundamentally, using `fork` in Python on macOS is unsafe and cannot be made so. It _might_ appear to work under some conditions on some macOS versions but can break at any time after changing pretty much anything.

**Comment by dwinings** [comment]
Thank you for the additional context, that helps out a lot. Seems like this is a known/out of scope thing, so I'm going to close the issue. 

My only comment is that it's probably worth a disclaimer somewhere more visible, since I imagine pretty much anyone who is trying to use fork() is also going to want to differentiate between parent/child.
