### ISSUE TITLE
Versions 1.3.2 and 1.3.3 are untagged

### ISSUE THREAD

**Issue by stefan6419846** [dvarrazzo/py-setproctitle#137]
At the moment, version 1.3.2 and 1.3.3 are not tagged on GitHub. This makes it harder to compare them. Could you please add the missing tags?

**Comment by dvarrazzo** [comment]
You are wrong.

**Comment by stefan6419846** [comment]
Sorry, I must have missed this, as GitHub shows Version 1.3.1 as the latest release: Version 1.3.1 was a regular release, version 1.3.2 and 1.3.3 are just tags.

**Comment by dvarrazzo** [comment]
I have removed those two releases too, as releasing happens on pypi, not on github.
