### ISSUE TITLE
Importing setproctitle shows bouncing dock icon on macOS

### ISSUE THREAD

**Issue by mario-grgic** [dvarrazzo/py-setproctitle#143]
I am using Python 3.13.0 on macOS 15.1 with setproctitle version 1.3.4. Just importing setproctitle in IPython launches bounding Dock icon that remains bounding during the entire session (until the process exits). This affects other packages that rely on setproctitle like pgcli etc.

**Comment by gershnik** [comment]
Thank you for reporting!
It reproduces for me too on macOS 15.0.1. Looks like something Apple ~~broke~~changed in the 15 update. Investigating...

**Comment by gershnik** [comment]
Ok I think I figured it out. PR will follow shortly. Recording findings here for future reference.

The first observation is that Node.js, which uses essentially the same code internally, doesn't suffer from this problem. The difference appears to be that `node` is a simple command line executable whereas Python on macOS is a full blown application with Info.plist, an icon etc.
It appears that newer macOS versions now unconditionally show Dock icon for what they recognize as a Mac application once it calls `LSApplicationCheckIn`. 
Fortunately this method takes the info dictionary for the calling application as a parameter allowing us to tweak it. The fix I settled on is to add [LSUIElement](https://developer.apple.com/documentation/bundleresources/information-property-list/lsuielement) key to it setting it to True. This appears to work perfectly in my testing.

Would be great to get some additional validation for this too. 
@mario-grgic if you have time and ability, could you install the version from my branch:
```bash
pip3 install git+https://github.com/gershnik/py-setproctitle.git@fix-143
```
and see if it fixes the problem for you? 

Thank you!

**Comment by mario-grgic** [comment]
@gershnik I verified the fix-143 branch and it fixes the problem here as well.  Thank you very much for such a fast response.

**Comment by gershnik** [comment]
Awesome, thank you so much!

**Comment by dvarrazzo** [comment]
Hello! Sorry, just seen this now.

Thank you for the report, will look into the MR and try to make a new release soon.

**Comment by mario-grgic** [comment]
@dvarrazzo Not sure if you missed this, but this has not been released yet. Would it be possible to create a new tag and include the fix for this?

**Comment by dvarrazzo** [comment]
Hi @mario-grgic 

Sorry, I've been confused with the macOS reports and then eventually this was lost in my backlog.

I'm juggling several tasks but I'll try to make a release within this week.

**Comment by dvarrazzo** [comment]
@mario-grgic setproctitle 1.3.5 released. Sorry about the delay.

**Comment by mario-grgic** [comment]
@dvarrazzo Awesome. Thank you.
