### ISSUE TITLE
Compilation fails on alpine linux 3.2

### ISSUE THREAD

**Issue by lxe** [dvarrazzo/py-setproctitle#44]
I'm running into the following issue when installing on alpine 3.2 (docker https://hub.docker.com/_/alpine/):

```
 /usr/include/linux/prctl.h:133:8: error: redefinition of 'struct prctl_mm_map'
     struct prctl_mm_map {
            ^
    In file included from src/spt_status.c:57:0:
    /usr/include/sys/prctl.h:88:8: note: originally defined here
     struct prctl_mm_map {
            ^
    error: command 'gcc' failed with exit status 1
```

Removing line https://github.com/dvarrazzo/py-setproctitle/blob/d346abbce4c554404a1447daf6e8e0822d6491a0/src/spt_status.c#L58 seems to fix this.

**Comment by tonyseek** [comment]
It seems to be similar to https://github.com/seccomp/libseccomp/issues/19

**Comment by jirutka** [comment]
I have the same problem, `#include <linux/prctl.h>` should be removed IMO.

**Comment by dvarrazzo** [comment]
I've tested that on Ubuntu 14.04 dropping `linux/prctl.h` works ok. Will test on some older linux deployment and if everything is ok will make a new release.

**Comment by yegorich** [comment]
Having the same issue with MUSL (as described in https://github.com/seccomp/libseccomp/issues/19) in Buildroot. Have also tried relative old toolchain Arago ARMv7 2011.09. py-setproctitle could be successfully compiled with both includes and without #include <linux/prctl.h>.

New release will be very appreciated.

**Comment by dvarrazzo** [comment]
Tested, merged in master
