### ISSUE TITLE
Just importing setproctitle affected /proc/{pid}/comm

### ISSUE THREAD

**Issue by tesseract2048** [dvarrazzo/py-setproctitle#45]
I've observed that `/proc/pid/comm` is changed during `spt_setup`, which is invoked in INIT_MODULE.
I think we'd better off leaving it unchanged until `setproctitle` or `getproctitle` is called.

**Comment by dvarrazzo** [comment]
Yes, I've thought about that, but that operation is better done before other modules have a chance to change environ.
