### ISSUE TITLE
setproctitle fails to build on windows

### ISSUE THREAD

**Issue by ssbarnea** [dvarrazzo/py-setproctitle#48]
```
  Complete output from command c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\so
rins\\AppData\\Local\\Temp\\pip-build-23dy4kk7\\setproctitle\\setup.py';exec(compile(getattr(tokenize, 'open', op
en)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\sorins\AppData\Local\Temp
\tmpjznl01c8pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'setproctitle' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for setproctitle
  Running setup.py clean for setproctitle
Failed to build setproctitle
Installing collected packages: setproctitle
  Running setup.py install for setproctitle ... error
    Complete output from command c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\
sorins\\AppData\\Local\\Temp\\pip-build-23dy4kk7\\setproctitle\\setup.py';exec(compile(getattr(tokenize, 'open',
open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\sorins\AppData\Local\
Temp\pip-r6xtk_js-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'setproctitle' extension
    error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "c:\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\sorins\\AppData\\Local\\
Temp\\pip-build-23dy4kk7\\setproctitle\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().r
eplace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\sorins\AppData\Local\Temp\pip-r6xtk_js-record
\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\sorins\AppData\Local\Temp\pip-build-23dy4kk7\setproctitle\
```
I should also mention that `vcvarsall.bat` is in PATH and that the other VC compilers are setup as
```
VS110COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VS120COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VS90COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
```

`Python 3.5.1 :: Anaconda 2.5.0 (64-bit)` -- but the problem also reproduces with Python 3 x64 from Python.org

**Comment by dvarrazzo** [comment]
Can you try compiling the `setuptools` branch instead?

**Comment by phumke** [comment]
+1 on the issue.  I attempted running setup from the branch and still had the error.

**Comment by dvarrazzo** [comment]
Out of curiosity... how is that module useful for windows users?

**Comment by ssbarnea** [comment]
I have no really idea about that as I reached this issue only because I tried to validate the cross-platform build on another package which listed `setproctitle` as a dependency. I do personally don't need the Windows build but others may.

**Comment by dvarrazzo** [comment]
Then please list setproctitle as an optional dependency. If there was a wheel build it'd be less of a problem (see issue #47), but I don't have the hardware resource or the time to build win wheels.

**Comment by ssbarnea** [comment]
Optional dependencies do not work when you are trying to do CI, because there you almost always need to install the most complex setup, so all optionals become mandatory, for testing purpose.

**Comment by phumke** [comment]
Hey @dvarrazzo, this module is used as a dependency by [airflow](https://github.com/airbnb/airflow).  I'm working in a windows environment and behind a firewall, so I needed to install this either from source or from a wheel file.

**Comment by dvarrazzo** [comment]
@phumke AFAICS setproctitle is not compatible with Python 3.5 on windows. I don't have expertise or resources to deal with this problem. It seems airflow doesn't lack such resources, so please provide a fix for issue #47 and you will have your wheel.

**Comment by waf** [comment]
I ran into this same issue (on Windows. Airflow pulled in this module as a dependency). I was able to fix it by installing the Visual Studio Build Tools as per [this stackoverflow post](https://stackoverflow.com/a/50210015/153006). It requires a couple gigabytes of dependencies, but does work.

**Comment by dvarrazzo** [comment]
@waf Binary builds for Windows can be provided if there is funding for them. Please see #47.
