### ISSUE TITLE
Importing setproctitle changes argv

### ISSUE THREAD

**Issue by MarcBruenink** [dvarrazzo/py-setproctitle#49]
Importing setproctitle changes argv in unexpected ways. 
Test case attached.
[test_setproctitle.zip](https://github.com/dvarrazzo/py-setproctitle/files/306097/test_setproctitle.zip)

Before import:
argv[0]: ./test_setproctitle
argv[1]: 1
argv[2]: 2
argv[3]: 3

After import:
argv[0]: ./test_setproctitle 1 2 3
argv[1]: 1 2 3
argv[2]: 2 3
argv[3]: 3

This is related to #45 and #46. But it is also different. 
This was very hard to find (took me 1 day). Also, it is a show stopper. Thus, the severity is quite high (for me).
Tested with 1.1.7 and 1.1.10.

**Comment by dvarrazzo** [comment]
This is how setproctitle works.

If it is a showstopper for you, don't use it.

**Comment by MarcBruenink** [comment]
This means you can only use the module in a restricted setting.
Please document the constraints in a prominent position.

**Comment by agibli** [comment]
Just ran into this. As a result, if setproctitle is imported during execution of a sitecustomize.py, it is not possible to pass arguments to python scripts:

```
$ touch test.py
$ echo "import setproctitle" > sitecustomize.py
$ export PYTHONPATH=.:$PYTHONPATH
$ python test.py --some-arg
python test.py --some-arg: can't open file 'test.py --some-arg': [Errno 2] No such file or directory
```

In my case the import of setproctitle was a consequence of importing pystatsd.

**Comment by wookayin** [comment]
Well, I think this is supper weird. Why? It changes the sensible default behavior.
