### ISSUE TITLE
getproctitle awkwardness

### ISSUE THREAD

**Issue by s0undt3ch** [dvarrazzo/py-setproctitle#55]
I've been working on a small class which is supposed to monitor processes and keep them up(restart when gone).
As an added bonus, that class allows one to pass in a process name which is then used by setproctitle to set that process name once the process is forked.

Here's the weird behavior I'm seeing.
The "process manager" is the parent process of all other started processes, I'm never calling setproctitle on it.
The code I'm using appends the name to the return of getproctitle.
If I start 3 processes and name them `p1`, `p2`, `p3`, the first final name is `<what's returned of getproctitle> p1`, the second, `<what's returned of getproctitle> p1 p2` and the third `<what's returned of getproctitle> p1 p2 p3`.

So even though the parent process never changes name, the child processes accumulate the appended names, why?

The processes are beeing forked, so they inherit the parents memory space, but this can't be it because the parent never changes names.

Oh, I'm using the multiprocessing module if that helps track down the behaviour.

Example python script:
```python
import time
import multiprocessing
import multiprocessing.util
import setproctitle

def after_fork(proc):
    setproctitle.setproctitle(setproctitle.getproctitle() + ' ' + proc.name)


def spin():
    while True:
        time.sleep(1)


processes = []
for n in range(3):
    proc = multiprocessing.Process(target=spin, name='foo {}'.format(n))
    multiprocessing.util.register_after_fork(proc, after_fork)
    processes.append(proc)
    proc.start()


while True:
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        break


for proc in processes:
    proc.terminate()
```
PS Output:
```
vampas     819  1.6  0.0  33172  9720 pts/2    S+   10:11   0:00 python /tmp/test.py                 
vampas     958  0.0  0.0  33172  8232 pts/2    S+   10:11   0:00 python /tmp/test.py foo 0           
vampas     960  0.0  0.0  33172  8232 pts/2    S+   10:11   0:00 python /tmp/test.py foo 0 foo 1     
vampas     961  0.0  0.0  33172  8232 pts/2    S+   10:11   0:00 python /tmp/test.py foo 0 foo 1 foo 2
```

**Comment by drougge** [comment]
This has nothing to do with setproctitle, it's a misunderstanding of how multiprocessing.util.register_after_fork works. Adding a print to after_fork makes this obvious:

```python
def after_fork(proc):
    print('%d setting %r' % (os.getpid(), setproctitle.getproctitle() + ' ' + proc.name))
    setproctitle.setproctitle(setproctitle.getproctitle() + ' ' + proc.name)
```

output:

```
28892 setting 'python spt_atfork.py foo 0'
28893 setting 'python spt_atfork.py foo 0'
28893 setting 'python spt_atfork.py foo 0 foo 1'
28894 setting 'python spt_atfork.py foo 0'
28894 setting 'python spt_atfork.py foo 0 foo 1'
28894 setting 'python spt_atfork.py foo 0 foo 1 foo 2'
```

So this should be closed.
