### ISSUE TITLE
need to set command name (/proc/nn/comm) separate to title

### ISSUE THREAD

**Issue by hmoffatt** [dvarrazzo/py-setproctitle#56]
It needs to be possible to set the command name for the linux process separately to the process title.

I tried to use setproctitle to simply remove the python3 prefix from the name in ps; eg
```
/path/to/python3 /some/path/to/my/script.py arg1 arg2
```
using
```
setproctitle(' '.join([os.path.realpath(__file__)] + sys.argv[1:]))
```
However, any use of setproctitle also changes what linux has in `/proc/<pid>/comm`, which is the command name and apparently limited to ~16 characters. Normally it is the name of the executable without any path eg bash, python3, apache2.

After using setproctitle with the above, `/proc/.../comm` reads `'/some/path/to/'` ie the first 16 characters of the process title.

**Comment by dvarrazzo** [comment]
What does it mean "it needs to be possible"? Is there a way in Linux to do it?

**Comment by Alphadelta14** [comment]
This is actually caused due to PR_SET_NAME (prctl) being invoked after argv is mangled. 

        PR_SET_NAME (since Linux 2.6.9)
              Set  the  name of the calling thread, using the value in the location pointed to by
              (char *) arg2.  The name can be up to 16 bytes long, including the terminating null
              byte.   (If  the length of the string, including the terminating null byte, exceeds
              16 bytes, the string is silently truncated.)  This is the same attribute  that  can
              be  set  via  pthread_setname_np(3) and retrieved using pthread_getname_np(3).  The
              attribute is likewise accessible via /proc/self/task/[tid]/comm, where tid  is  the
              name of the calling thread.

historically, PR_SET_NAME had been [erroneously documented](https://www.freebsd.org/cgi/man.cgi?query=prctl&sektion=2&apropos=0&manpath=CentOS+6.6) to update process name, but it actually meant thread name (/comm).

**Comment by dvarrazzo** [comment]
Solving by avoid initialisation at import time in 1.2.
