### ISSUE TITLE
Install error on Win7

### ISSUE THREAD

**Issue by p0f1g1st** [dvarrazzo/py-setproctitle#58]
Try to install setproctitle on Win7 (64-bit, python 3.6) but get error:
`Collecting setproctitle
  Using cached https://files.pythonhosted.org/packages/5a/0d/dc0d2234aacba6cf1a7
29964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz
Building wheels for collected packages: setproctitle
  Running setup.py bdist_wheel for setproctitle ... error
  Complete output from command c:\users\user\appdata\local\programs\python\pytho
n36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\App
Data\\Local\\Temp\\pip-install-9z6x3ghu\\setproctitle\\setup.py';f=getattr(token
ize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(
compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\User\AppData\Local\Tem
p\pip-wheel-gs8ihca8 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'setproctitle' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C+
+ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for setproctitle
  Running setup.py clean for setproctitle
Failed to build setproctitle
Installing collected packages: setproctitle
  Running setup.py install for setproctitle ... error
    Complete output from command c:\users\user\appdata\local\programs\python\pyt
hon36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\A
ppData\\Local\\Temp\\pip-install-9z6x3ghu\\setproctitle\\setup.py';f=getattr(tok
enize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exe
c(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local
\Temp\pip-record-_bpsa5t_\install-record.txt --single-version-externally-managed
 --compile:
    running install
    running build
    running build_ext
    building 'setproctitle' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\user\appdata\local\programs\python\python36\python.exe -u -c "
import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip
-install-9z6x3ghu\\setproctitle\\setup.py';f=getattr(tokenize, 'open', open)(__f
ile__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__
, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-record-_bpsa5t
_\install-record.txt --single-version-externally-managed --compile" failed with
error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-9z6x3ghu\setproctit
le\`

But I have Visual C++ 14.16 version x64 and x86. I have no idea why it isn't working for me

**Comment by dvarrazzo** [comment]
I have no idea but it's not a bug in our problems. Please look for helps with setuptools people.
