### ISSUE TITLE
Unable to install in cygwin

### ISSUE THREAD

**Issue by DjLegolas** [dvarrazzo/py-setproctitle#63]
On `cygwin` 64bit, I wasn't able to install with Python 2.7, 3.6, 3.7.
I ran the command `pythonX.Y -m pip install setproctitle` and recieved an error:
```
gcc -shared -Wl,--enable-auto-image-base build/temp.cygwin-3.0.7-x86_64-3.6/src/setproctitle.o build/temp.cygwin-3.0.7-x86_64-3.6/src/spt_debug.o build/temp.cygwin-3.0.7-x86_64-3.6/src/spt_setup.o build/temp.cygwin-3.0.7-x86_64-3.6/src/spt_status.o build/temp.cygwin-3.0.7-x86_64-3.6/src/spt_strlcpy.o -L/usr/lib/python3.6/config -L/usr/lib -lpython3.6m -o build/lib.cygwin-3.0.7-x86_64-3.6/setproctitle.cpython-36m-x86_64-cygwin.dll
build/temp.cygwin-3.0.7-x86_64-3.6/src/spt_setup.o: In function `get_argc_argv':
/tmp/pip-install-h24jpxug/setproctitle/src/spt_setup.c:373: undefined reference to `Py_GetArgcArgv'
/tmp/pip-install-h24jpxug/setproctitle/src/spt_setup.c:373:(.text+0xc9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `Py_GetArgcArgv'
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```
`python-dev` is installed for each of the versions.
It happens with source code as well.

It appears to be related to the python's function `Py_GetArgcArgv` which is declared internally only. I was able to fix this by one of the following ways:
1. Comment out the line https://github.com/dvarrazzo/py-setproctitle/blob/d6a43b14470d806984d03079164ba05cebb997d0/src/spt_setup.c#L373
2. Creating a new `spt_python.c` file, with an implementation of the function. It doesn't return anything.

Both ways are basic and needs a better solution.

**Comment by dvarrazzo** [comment]
Compiling on Cygwin is not supported. If you would like Cygwin support to be added you have a few options:

- propose a patch for the issue and create a task on appveyor to to ensure build works
- support financially the project to have the feature added.

**Comment by DUOLabs333** [comment]
@dvarrazzo Really? It's pretty easy to fix too, and it works fine on my end.
