### ISSUE TITLE
Not working with PyInstaller

### ISSUE THREAD

**Issue by arossert** [dvarrazzo/py-setproctitle#64]
I'm not sure if this issue is in `setproctitle` but when I try to use it with a bundled app using PyInstaller it is just not working.

Here is a simple example:
sample.py

```
import setproctitle

print setproctitle.getproctitle()
setproctitle.setproctitle("test")
print setproctitle.getproctitle()
```
output:
```
arossert$ python sample.py
python sample.py
test
```

Then I use PyInstaller
`pyinstaller sample.py`

Running the code:
```
arossert$ dist/sample/sample


```
Output is empty

Tested on MacOS.

**Comment by mlasevich** [comment]
+1

Having same issue with MacOS but it works in Ubuntu

**Comment by dvarrazzo** [comment]
Please open a bug with pyinstaller.
