### ISSUE TITLE
pip2 install setproctitle should not require a gcc compiler???

### ISSUE THREAD

**Issue by paulpoco** [dvarrazzo/py-setproctitle#65]
In a Docker image linux.   Trying to update Deluge to 2.0.3 but it requires setproctitle which then during the install complains that there is no GCC compiler.

Please make the package a Binary so you do not need to have GCC.

Running setup.py install for setproctitle ... error
    ERROR: Complete output from command /usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-4RGsNX/setproctitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-S5Hhti/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'setproctitle' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -DHAVE_SYS_PRCTL_H=1 -DSPT_VERSION=1.1.10 -I/usr/include/python2.7 -c src/setproctitle.c -o build/temp.linux-x86_64-2.7/src/setproctitle.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/usr/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-4RGsNX/setproctitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-S5Hhti/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4RGsNX/setproctitle/

**Comment by dvarrazzo** [comment]
Can you provide a patch to build the wheels in Travis? Thank you.

**Comment by jayvdb** [comment]
This is a dup of https://github.com/dvarrazzo/py-setproctitle/issues/47

**Comment by dvarrazzo** [comment]
Adding a travis job to create wheels.

**Comment by dvarrazzo** [comment]
Closing as dupe
