### ISSUE TITLE
Solaris 10 and 11

### ISSUE THREAD

**Issue by adiroiban** [dvarrazzo/py-setproctitle#7]
Hi,

I just want to report that this almost works on Solaris and maybe this help other people working on this

On solaris 10 you need to use `/usr/ucb/ps -auxww` ... for solaris 11 I use `ps auxww`

You will need to run the command as the same use account ... and the result is padded with may space characters

it will not work with normal PS command

```
-bash-3.2$ /usr/ucb/ps -auxww | grep 21084 
chevah   21084  0.2  0.64943241800 ?        S 10:43:46  0:05 chevah-server-service

                 -c
chevah   21115  0.0  0.1 1736 1256 pts/1    S 10:44:14  0:00 grep 21084

-bash-3.2$ ps -ef | grep 21084
  chevah 21084     1   0 10:43:46 ?           0:07 /opt/Chevah-Server/bin/python -m chevah.server.__init__ start --pid /var/run/
```

If I run the command as another user I see

```
-bash-3.2$ sudo su - buildslave
-bash-3.2$ /usr/ucb/ps -auxww | grep 21084
chevah   21084  0.0  0.64943241800 ?        S 10:43:46  0:05 /opt/Chevah-Server/bin/python -m chevah.server.__init__ start --pid /var/run/
buildsla 21128  0.0  0.1 1736 1256 pts/1    S 10:48:04  0:00 grep 21084
```

Thanks!

**Comment by dvarrazzo** [comment]
Solaris is dead, right?

**Comment by adiroiban** [comment]
Yep. RIP and I hope it will never come back. Thanks for the cleanup :)
