### ISSUE TITLE
Conflict with darwin.cython lib on Catalina iOS & python 3.7

### ISSUE THREAD

**Issue by maximilianolucius** [dvarrazzo/py-setproctitle#71]
I get an error when importing setproctitle on my script: I use python 3.7 and iOS Catalina. It is about darwin cython lib.

I found that this issue disappear in python3.8: is there a work around to use steproctitle on python 3.6 o 3.7?

Rgrs,

Max

**Comment by dvarrazzo** [comment]
Sorry but "I get an error" is very unhelpful.

Other people don't have this problem. I think you can google around for your error message.

I don't use iOS personally so I can't debug it.
