### ISSUE TITLE
Add to README about python-prctl

### ISSUE THREAD

**Issue by socketpair** [dvarrazzo/py-setproctitle#73]
https://github.com/seveas/python-prctl

it has 

```
prctl.set_name(process_name)
prctl.set_proctitle(process_name)
```

but both are not portable. Also this library does not support Python 3.8 yet. And the more important -- it is not packaged in Fedora.

**Comment by dvarrazzo** [comment]
I don't understand exactly what you are asking.

- Are you saying that python-prctl wraps prctl in a non-prtable way? Might be, but this is not that projectr 
- When you say *this library* does not support Python 3.8, are you referring to python-prctl or to setproctitle?

The only thing I can say for sure is that Fedora packages are Fedora responsibility. I still don't understand if you are talking about this project (py-setproctitle) or about that unrelated project (python-prctl), but either case this is not the right place to ask for fedora packages.

**Comment by dvarrazzo** [comment]
Ah, do you mean to cite python-prctl in the readme as an alternative in *Other known implementations and discussions*. No, I don't really care so much about it. That section was written 8 years ago to state where this project positions itself in the current state of the art. Now I understand this project is a reference and others should have a section to state why their project is better than this, I don't want to keep on chasing all the alternatives. Probably that section will be removed from the readme.

**Comment by socketpair** [comment]
@dvarrazzo Yep, exactly. I wanted you to mention python-prctl in README. It's better to leave the section. It explains why your library is better than others. It helps to choose from alternatives. For example, Cryptography library states why it is better than thousands of other implementations.
