### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [dvarrazzo/py-setproctitle#75]
The last release is 4 years old, could you make a new one?

**Comment by dvarrazzo** [comment]
I see support for bsd since, which is surely worth release. But what is that you are interested into?

**Comment by randy3k** [comment]
It will be great if you could ship wheels directly. Especially nowadays [cibuildwheel](https://github.com/joerick/cibuildwheel) makes it super easy via github actions.

**Comment by dvarrazzo** [comment]
@randy3k that's a different topic from this one.
