### ISSUE TITLE
Python 3.9: undefined symbol: Py_GetArgcArgv in setproctitle

### ISSUE THREAD

**Issue by praiskup** [dvarrazzo/py-setproctitle#76]
Fedora 33 is built against (at this moment pre-release?) Python 3.9, and we
have problems with linking of the compiled setproctitle:
```
>>> import setproctitle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib64/python3.9/site-packages/setproctitle.cpython-39-x86_64-linux-gnu.so: undefined symbol: Py_GetArgcArgv
```
That symbol isn't exported in the new libpython 3.9 version.  For more info:
https://bugzilla.redhat.com/show_bug.cgi?id=1792059

**Comment by hroncok** [comment]
> (at this moment pre-release?) Python 3.9

Yes, 3.9.0b1.

**Comment by dvarrazzo** [comment]
Reported upstream in https://bugs.python.org/issue15577

**Comment by vstinner** [comment]
I created https://bugs.python.org/issue40910 on Python upstream.

**Comment by dvarrazzo** [comment]
@vstinner thank you: being nosy on it. To release a new version as soon as I know how to support Py 3.9.

**Comment by dvarrazzo** [comment]
Depending on https://github.com/python/cpython/pull/20723

**Comment by vstinner** [comment]
See also https://bugs.python.org/issue23427

**Comment by vstinner** [comment]
> I created https://bugs.python.org/issue40910 on Python upstream.

Fixed in 3.9 and master Python branches.

**Comment by vstinner** [comment]
I created https://github.com/python/cpython/pull/20729 to make PyConfig.orig_argv public and to add sys.orig_argv.

**Comment by dvarrazzo** [comment]
Fixed in most recent 3.9 beta release.

**Comment by Bharathsanthakumar** [comment]
@dvarrazzo I struck with a build env of python3.3, I am experiencing the same issue while importing setproctitle. Possible to fix by myself in Python3.3 source?

**Comment by dvarrazzo** [comment]
Python 3.3 is unsupported. If it was supported in the past, you can use git history to recover a working version.
