### ISSUE TITLE
Command line argumests lost

### ISSUE THREAD

**Issue by tibor95** [dvarrazzo/py-setproctitle#81]
Hi,
it is not clear to me what is expected behavior, let say I run
` python test_script.py  -a -b`
and renaming it inside it to "other_script.py"

```
$ ps -ao pid,cmd,args
  PID CMD                      COMMAND
18762 other_script.py          other_script.py
```
arguments "-a -b" are not listed anywhere. Is it expected? Should I "fake" then reading args[1:] from inside the python and putting them into new name?

Anyway, thanks for interesting tool

**Comment by dvarrazzo** [comment]
Yes, it is expected. The string changed is the entire command line, not only the first argument.
