### ISSUE TITLE
MacOS Python3.7 Symbol not found: _Py_GetArgcArgv

### ISSUE THREAD

**Issue by wdahab** [dvarrazzo/py-setproctitle#82]
Ran into an import error with setproctitle (while setting up ray.io which has a dependency on setproctitle after ray>=0.8.0). I have 1.1.10 installed, using MacOS Catalina with the xcode default Python 3.7.3.
```
>>> import setproctitle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/wdahab/.virtualenvs/raytest/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so, 2): Symbol not found: _Py_GetArgcArgv
  Referenced from: /Users/wdahab/.virtualenvs/raytest/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/wdahab/.virtualenvs/raytest/lib/python3.7/site-packages/setproctitle.cpython-37m-darwin.so
```

**Comment by potiuk** [comment]
I would love to get that sorted out. This is a big problem for one of our users at https://github.com/apache/airflow/issues/10961 and we would love this one to be fixed. We cannot do much on our end in Apache Airflow to help our user.

**Comment by wdahab** [comment]
So I found that everything works fine after upgrading to Python 3.8.5 (can't speak to other 3.8.x versions). Doesn't particularly help if someone else can't get away from 3.7, but for my use case it was good enough.

**Comment by potiuk** [comment]
Yeah it is all explained in https://stackoverflow.com/questions/60684146/airflow-initdb-undefined-symbol-py-getargcargv so it is a problem of someone who cannot upgrade. If it is a difficult one to fix, I think this should be closed with the advice "please upgrade". Then it would give the user an argument to whoever or whatever is blocking the patch upgrade (it's  not very smart to block patchlevel upgrades)

but if (maybe?) this one is easy to fix, then maybe that's the way to go :). @dvarrazzo  :)

**Comment by Jorricks** [comment]
> So I found that everything works fine after upgrading to Python 3.8.5 (can't speak to other 3.8.x versions). Doesn't particularly help if someone else can't get away from 3.7, but for my use case it was good enough.

On Python 3.8.2, there is still the same issue. I didn't see this issue so I opened my own 🤷‍♂️ .

However, I am wondering @wdahab, are you using the python3 that comes by default from Mac or from `XCode`?
I haven't read anyone with problems who installed python3 using brew or directly with the executable from [python.org](https://python.org).
