### ISSUE TITLE
FreeBSD 12 python shows up twice

### ISSUE THREAD

**Issue by syleishere** [dvarrazzo/py-setproctitle#86]
Process shows up with python in front of process name, then again at the end.

90570  7  S+   0:00.09 python: new proc title as seen in top (python3.8)

CODE:

import setproctitle
import time

setproctitle.setproctitle('new proc title as seen in top')
time.sleep(100)

**Comment by dvarrazzo** [comment]
That's what FreeBSD does, I guess. I doubt it can be changed.
