### ISSUE TITLE
Segmentation fault after call setproctitle

### ISSUE THREAD

**Issue by lexsos** [dvarrazzo/py-setproctitle#88]
There is a trouble with calling `setproctitle` function after calling `os.environ.clear()`. The python process fall with `Segmentation fault` error. Example:
```python
import os

from setproctitle import setproctitle


def main():
    print("Starting")
    os.environ.clear()
    setproctitle("Test")
    print("Started")


if __name__ == '__main__':
    main()
```
I run it in docker with image `python:3.8` and with `setproctitle==1.2`.

**Comment by dvarrazzo** [comment]
Yup, confirmed, thank you for the report.
