### ISSUE TITLE
win32: error C2099: initializer is not a constant

### ISSUE THREAD

**Issue by petrutlucian94** [dvarrazzo/py-setproctitle#89]
setproctitle 1.2 cannot be compiled on Windows using Visual Studio: http://paste.openstack.org/raw/800723/

We're getting this error:  src/spt_setup.c(454): error C2099: initializer is not a constant

I think one option would be to get VS to use a newer C or C++ standard. The alternative would be to change this specific initialization.

**Comment by petrutlucian94** [comment]
Related issue: https://github.com/dbcli/pgcli/issues/1225

**Comment by dvarrazzo** [comment]
Hello, thank you for reporting the issue.

setproctitle is not officially supported on Windows. I haven't tried building on it and there is no CI system testing it.

1. If you provide a patch to fix the build issues I can apply it, but I can make no guarantee it will break again in the future.
2. If you set up testing on Github Actions I can fix the code myself.
3. If you provide a way to build binary packages for windows on Github Actions I can release them.
4. With the sponsorship covering the couple of days I should work, I can try and create binary packages for windows: see #47.

Thank you!

**Comment by petrutlucian94** [comment]
Hi, no worries. I saw a few ``#ifndef _WIN32`` checks so I assumed it's supported. I can provide a fix right away. I'll try to find some time for a github action as well in order to build Windows wheels.

**Comment by petrutlucian94** [comment]
Done, I've submitted a PR fixing this issue, also including Github actions.
