### ISSUE TITLE
Wheel support for linux aarch64 [arm64]

### ISSUE THREAD

**Issue by odidev** [dvarrazzo/py-setproctitle#91]
Summary
Installing py-setproctitle on aarch64 via pip using command "pip3 install py-setproctitle" tries to build wheel from source code

Problem description
py-setproctitle doesn't have wheel for aarch64 on PyPI repository. So, while installing py-setproctitle via pip on aarch64, pip builds wheel for same resulting in it takes more time to install py-setproctitle. Making wheel available for aarch64 will benefit aarch64 users by minimizing py-setproctitle installation time.

Expected Output
Pip should be able to download py-setproctitle wheel from PyPI repository rather than building it from source code.

@py-setproctitle-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make py-setproctitle wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by dvarrazzo** [comment]
Hi @odidev,

setproctitle is built on Github Actions: if you provide a changeset for it and make it create the right packages I will distribute them.

Note that in #90 the Windows build is being added, so we can expect some merge conflicts there if I haven't reviewed and merged that branch already.

**Comment by odidev** [comment]
@dvarrazzo Thanks for your quick response, I will start working on it and will raise a PR.

**Comment by dvarrazzo** [comment]
Works on #90 are finished, so you can work on `.github/workflow/packages.yml` without too much fear of conflicts.
