### ISSUE TITLE
Too many redundant null chars in `/proc/[pid]/cmdline` on Linux

### ISSUE THREAD

**Issue by XuehaiPan** [dvarrazzo/py-setproctitle#97]
`setproctitle` writes a fixed length of string to `/proc/[pid]/cmdline` file on Linux, which may have many redundant tailling `\x00` chars. This will cause incorrect result of cmdline which queried by other library.

`man proc`:
> /proc/[pid]/cmdline
>               This  read-only  file holds the complete command line for the process, unless the process is a zombie.  In the latter case, there is nothing in this file: that is, a read on this file will return 0 characters.   The  command-line  arguments  appear  in  this file as a set of strings separated by null bytes ('\0'), with a further null byte after the last string.

```python
In [1]: from setproctitle import setproctitle

In [2]: setproctitle('Process Title')

In [3]: import os
   ...: with open(f'/proc/{os.getpid()}/cmdline', mode='rt') as file:
   ...:     cmdline = file.read()
   ...:     

In [4]: cmdline
Out[4]: 'Process Title\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

In [5]: import psutil

In [6]: process = psutil.Process()

In [7]: process.cmdline()
Out[7]: 
['Process Title', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
```

Source code of `psutil.Process.cmdline()`:

https://github.com/giampaolo/psutil/blob/release-5.8.0/psutil/_pslinux.py#L1694-L1717

**Comment by dvarrazzo** [comment]
I don't think there is an alternative way to do it.
