### ISSUE TITLE
Question: Sponsored by Data Dog?

### ISSUE THREAD

**Issue by esmail** [dvarrazzo/py-setproctitle#98]
Hey :) I was reviewing our requirements file and noticed that we're using your package because it's [required](https://docs.datadoghq.com/integrations/gunicorn/#installation) by the Datadog agent for use with Gunicorn, both which we use. Just kinda made me curious if they sponsor the project.

Cheers,
Esmail

**Comment by dvarrazzo** [comment]
No they don't. Thank you for asking :)
